name: Check Markdown Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  markdown-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Markdown Lint
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: "."
          config_file: ".markdownlint.json"
